### ISSUE TITLE
update parameters via API

### ISSUE THREAD

**Issue by perlokan** [kakopappa/sinric#141]
Hi,
can I change a parameter of a device via API?
For example the temperature of a thermostat.
Can you give me a curl example?
Thanks

**Comment by kakopappa** [comment]
Right now it's allowed through only websockets (may be you know this already). 

can you tell me why do you want to do this? are you using Pi ?

**Comment by perlokan** [comment]
Yes I use PI.

**Comment by kakopappa** [comment]
I will update the API in the next milestone and update the API spec and sorry about the delay. 

I am spending lot of time these days on irdevkit.com with the new module testing.

**Comment by perlokan** [comment]
Thank you.
It would be important for me to have also a timestamp for each device when it receives an Alexa command. Do you think you can add it?

**Comment by greno** [comment]
I would also like to have the ability to send the current temperature to the server for my thermostat device.  Right now it looks like I can only send the target temperature, rather than the current temperature.  Using Arduino.

BTW, the API is working great for me. Very easy to set up and use.  Thanks!

**Comment by kakopappa** [comment]
added to 1.4 release. check the api documentation for examples.
