### ISSUE TITLE
Sinric is down, Error 525

### ISSUE THREAD

**Issue by Deimos1994** [kakopappa/sinric#210]
When using HTTPS: SSL handshake failed, Error 525
When using HTTP: Web server is down, Error 521

**Comment by amitabh-srivastav** [comment]
@kakopappa Host error. probably server is down.
Error 525 Ray ID: 49aaa202386469f5 • 2019-01-17 17:44:58 UTC
SSL handshake failed

**Comment by malhotrasujeet** [comment]
Alexa devices gone unresponsive. 
Sinric skill not getting enabled. shows the same error as mentioned above by @amitabh-srivastav

**Comment by aryeguetta** [comment]
Just wanted to learn the skill with Alexa and Google and saw that Error 525 SSL handshake failed.
Is that error fixable? thanks for a great skill. Hope it will be back soon.

**Comment by CptZeroG** [comment]
Auch! Same problem...half of my house is down...I hope that will work back soon

**Comment by GaryLittlemore** [comment]
My devices are down too :-(

**Comment by acostadaniel1** [comment]
Well.. never works as expected for long time, but reconnecting with Google home, it was working for a few days..
But now the server is down :(

**Comment by kakopappa** [comment]
thanks for letting me know. I have fixed the issue and all services should be back to normal now.

The reason was I had a cron job to renew the server certificate in the midnight. For some reason, certbot (letsencrypt) failed today and it did not release port 443 for the Nginx server after it crashed. So no one was listening on port 443. thus

Error 525 Ray ID: 49acc4514db181b6 • 2019-01-17 23:57:55 UTC
SSL handshake failed

**Comment by Deimos1994** [comment]
Works now, thanks @kakopappa, closing.
