### ISSUE TITLE
SINRIC with Google Assistant

### ISSUE THREAD

**Issue by saikhurana** [kakopappa/sinric#65]
hey,
is there a way we can use SINRIC with google assistant. i know that you have applied for google to approve. but is there a way we can use is before-hand using DEV-account or something like we do while doing beta testing for Alexa.

**Comment by kakopappa** [comment]
Google is not so user friendly when it comes to home automation skills. They asked me to send two devices for testing since Sinric does not produce any hardware it didn't get approved. Can use it only in dev mode. 

I have to figure out how everyone can use it in dev mode.

https://github.com/kakopappa/sinric/issues/6

**Comment by saikhurana** [comment]
If you want i cam assemble hardware for them to look at.

**Comment by kakopappa** [comment]
hi, can you drop me your email address here?

**Comment by saikhurana** [comment]
There you go.
saikhurana1@gmail.com

**Comment by kakopappa** [comment]
I think I found a way around last night. I have to make some changes and test this first. If this doesn't work we have to send a device for them to test.

I highly appriciate your enthusiasm

**Comment by saikhurana** [comment]
I would love to be the first Beta Tester.

**Comment by kakopappa** [comment]
Guys, I have updated the site with Google Home support now. Enjoy!

https://github.com/kakopappa/sinric/wiki/How-to-use-Google-Home

**Comment by kakopappa** [comment]
Since google support is available, I will close this issue. Thanks guys.
