### ISSUE TITLE
Problem with alexa skill connecting to sinric

### ISSUE THREAD

**Issue by noobipaul** [kakopappa/sinric#89]
Hi @kakopappa . I have been using Alexa controlled esp8266 switches via sinric for a while now without any problems.
This evening they seemed to have stopped.  I disabled the sinric Amazon skill, then tried to enable it again but get the error shown in attached screen shot? Any ideas what the problem is? Thanks.
![screenshot_20180710-223500_chrome canary](https://user-images.githubusercontent.com/16270547/42539034-a89d1ae0-8491-11e8-9155-e0d43dce7455.jpg)

**Comment by kakopappa** [comment]
Hello. Can you try now? Let me know if you still have this problem

**Comment by noobipaul** [comment]
Thank you. Working now :)

**Comment by minimatte77** [comment]
Hi @kakopappa . I have been using Alexa controlled esp8266 switches via sinric for a while now without any problems.
This evening they seemed to have stopped. I disabled the sinric Amazon skill, then tried to enable it again but get the error shown in attached screen shot? Any ideas what the problem is? Thanks.

I have the same problem, what can it depend on?
Thank you
